product:
  name: "Spotify"
  description: "Music streaming platform"

reddit:
  keywords:
    - "cancel"
    - "subscription"
    - "price increase"
    - "switching"
    - "leaving"
    - "bug"
    - "support"
  
  subreddits:
    - "spotify"
    - "truespotify"


  fetch:
    post_limit: 50
    comment_limit: 200
    sort: "new"      # new | hot | top
    time_filter: "month"   # day | week | month | year | all
